# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy Next.js site to Render

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # unit test job
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
            version: 7
            run_install: true
      - name: Install Dependence
        run: pnpm install --frozen-lockfile
  
  deploy:
    name: Deploy
    needs: [test] # Our tests must pass in order to run the deploy job
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          api-key: ${{ secrets.RENDER_TOKEN }}
          service-id: ${{ secrets.SERVICE_ID }}